### ISSUE TITLE
Mapa mental 

### ISSUE THREAD

**Issue by Maritza2893** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Maritza2893#2]
![Conjuntos y relaciones   (2)](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Maritza2893/assets/143298981/232a6e08-2db4-49e8-843e-f70638fa1c2d)

**Comment by josealfredo79** [comment]
Calificacion

**Comment by LuisAlexisMorales** [comment]
Manejo conceptual:25%
Relación entre concepto:25%
Calidad de la presentación:22%
Jerarquía:25%
Total:97%. CalFinal:19%
Calificado por el equipo de: Luis Alexis Morales

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
